import js from '@eslint/js';
import globals from 'globals';

// Browser-side application code (loaded directly in the page).
const browserSrc = {
  files: ['src/**/*.{js,mjs,cjs}', 'examples/**/*.{js,mjs,cjs}'],
  languageOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    globals: { ...globals.browser, ...globals.serviceworker },
  },
};

// A few persona-builder modules run in both browser and Node (tests import them);
// they reference `Buffer` for base64 encode/decode in the Node path.
const dualEnvSrc = {
  files: ['src/persona-builder/**/*.{js,mjs,cjs}'],
  languageOptions: {
    globals: { ...globals.browser, ...globals.node },
  },
};

const nodeFiles = {
  files: [
    'tools/**/*.{js,mjs,cjs}',
    'tests/**/*.{js,mjs,cjs}',
    'packages/**/*.{js,mjs,cjs}',
    '.claude/hooks/**/*.{js,mjs,cjs}',
    '*.config.{js,mjs,cjs}',
    'playwright.config.mjs',
    'vitest.config.mjs',
  ],
  languageOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    globals: { ...globals.node },
  },
};

// Playwright e2e tests run in Node but pass callbacks to page.evaluate()
// where browser globals (`document`, `window`, `localStorage`) are legal.
const e2eTests = {
  files: ['tests/e2e/**/*.{js,mjs,cjs}'],
  languageOptions: {
    globals: { ...globals.node, ...globals.browser },
  },
};

// Vitest suites that opt into the jsdom environment (`// @vitest-environment
// jsdom`) exercise real DOM nodes, so `document` / `window` are legal there.
const jsdomTests = {
  files: [
    'tests/dom-helpers.test.mjs',
    'tests/ui-module-graph.test.mjs',
    'tests/i18n.test.mjs',
    'tests/ui-modules.test.mjs',
  ],
  languageOptions: {
    globals: { ...globals.node, ...globals.browser },
  },
};

const sharedRules = {
  rules: {
    'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-prototype-builtins': 'off',
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-useless-escape': 'off',
    'no-regex-spaces': 'off',
  },
};

export default [
  {
    ignores: [
      'dist/**',
      '_site/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'archive/**',
      'synthetic-identity-pool/**',
      // Everything under packages/sandbox-fixtures/ except hand-authored
      // entry files is generated by tools/build-fixture-package.mjs.
      'packages/sandbox-fixtures/lib/**',
      'packages/sandbox-fixtures/bundles/**',
      'packages/sandbox-fixtures/brands/**',
      'packages/sandbox-fixtures/enrichment/**',
      'packages/sandbox-fixtures/personas/**',
      'packages/sandbox-fixtures/src/data/**',
      'packages/sandbox-fixtures/dist/**',
      'packages/sandbox-fixtures-py/**',
      'packages/sandbox-mcp/dist/**',
      'examples/**/vendor/**',
      'src/vendor/**',
      'coverage/**',
      '.lighthouseci/**',
    ],
  },
  js.configs.recommended,
  browserSrc,
  dualEnvSrc,
  nodeFiles,
  e2eTests,
  jsdomTests,
  sharedRules,
];
