// ATM Locator domain UI — Phase 2.3 UX revision.
//
// The ATM domain ships infrastructure data (a public directory of LFI-owned
// ATMs) rather than customer behaviour. The user picks "ATM Locator" from
// the domain chip; the persona library is replaced by an ATM picker — a
// scrollable, filterable list of every ATM in the directory; the right pane
// renders the selected ATM as a spec-driven field tree.
//
// State surfaces:
//   - state.bundle.atms  — flat array of ATM records, generated by
//     src/generator/atm/index.js (LFI-redacted per profile).
//   - state.atmId        — the selected ATM's ATMId, or null for the
//     directory-overview landing.
//
// URL contract:
//   ?domain=atm&lfi=median&seed=47131&atm=<ATMId>
//
// No persona library, no JTBD rail, no segment filter, no compare-mode,
// no coverage meter, no underwriting panel — all are persona-shaped
// affordances with no ATM analogue. They are suppressed via the
// `.is-atm` class hung on .persona-pane while the ATM domain is active.

import { leafFields } from '../shared/spec-helpers.js';
import { renderFieldTree } from './field-tree.js';
import { track } from '../analytics.js';
// `track` is imported for the endpoint_nav event below (already in
// ALLOWED_EVENTS); ATM-specific selection is intentionally NOT instrumented
// to keep the EXP-21 allowlist tight — add when there's a clear research
// question that needs it.

export function createAtm(deps) {
  const { state, el, syncControls, pushPermalink } = deps;

  function renderAtmBundle() {
    if (!state.endpoint || !state.spec.endpoints?.[state.endpoint]) {
      state.endpoint =
        state.domains?.[state.domain]?.defaultEndpoint ??
        Object.keys(state.spec.endpoints ?? {})[0] ??
        null;
    }
    // Default selection: first ATM in the directory. Switching LFI may shrink
    // the fleet so an ATMId from a richer profile no longer exists — fall
    // back to the first ATM in that case.
    const atms = state.bundle?.atms ?? [];
    if (atms.length > 0 && (!state.atmId || !atms.some((a) => a.ATMId === state.atmId))) {
      state.atmId = atms[0].ATMId;
    } else if (atms.length === 0) {
      state.atmId = null;
    }

    showAtmPaneChrome();
    syncControls();
    renderAtmNavigator();
    renderAtmPicker();
    renderAtmPayload();
  }

  // The persona-pane carries the persona library (segment rail, JTBD rail,
  // stress-filter chip, persona-list-footer "+ Build a custom persona" CTA).
  // None of those make sense for an LFI's ATM directory, so we hide them
  // while the ATM domain is active. createAtm.restorePersonaChrome() reverses
  // this when leaving the domain.
  function showAtmPaneChrome() {
    const pane = document.querySelector('.persona-pane');
    if (!pane) return;
    pane.classList.add('is-atm');
    const header = pane.querySelector('.pane-header .pane-header-text');
    if (header) header.textContent = 'ATM directory';
    const rail = pane.querySelector('.pane-rail .pane-rail-label');
    if (rail) rail.textContent = 'ATM directory';
  }

  function renderAtmNavigator() {
    const nav = document.getElementById('nav-tree');
    if (!nav) return;
    nav.replaceChildren();
    const dom = state.domains?.[state.domain];
    const wrap = el('div', { class: 'nav-account is-bundle' });
    wrap.appendChild(el('div', { class: 'nav-account-header', text: dom?.label ?? 'ATM Locator' }));
    const inScope = state.spec?.inScopePaths ?? Object.keys(state.spec?.endpoints ?? {});
    for (const ep of inScope) {
      const isActive = state.endpoint === ep;
      const btn = el(
        'button',
        {
          class: `nav-endpoint${isActive ? ' active' : ''}`,
          attrs: { 'aria-current': isActive ? 'true' : null },
          dataset: { endpoint: ep },
          onClick: () => {
            state.endpoint = ep;
            renderAtmNavigator();
            renderAtmPayload();
            pushPermalink();
            track('endpoint_nav', { endpoint: ep, domain: state.domain });
          },
        },
        el('span', { class: 'nav-endpoint-label', text: ep }),
      );
      wrap.appendChild(btn);
    }
    nav.appendChild(wrap);
  }

  // ATM picker — replaces the persona library. Filter input + scrollable
  // list keyed on ATMId. Each row shows ATMId, district + town, availability
  // status chip. Click selects the ATM; the selection is round-tripped via
  // ?atm=<ATMId> in the URL.
  function renderAtmPicker() {
    const host = document.getElementById('persona-list');
    if (!host) return;
    host.replaceChildren();
    host.setAttribute('role', 'listbox');
    host.setAttribute('aria-label', 'ATM directory');

    const atms = state.bundle?.atms ?? [];
    const filter = (state.atmFilter ?? '').trim().toLowerCase();

    const filterBar = el('div', { class: 'atm-filter-bar' });
    const input = el('input', {
      class: 'atm-filter-input',
      attrs: {
        type: 'search',
        placeholder: 'Filter by ATMId, district, town…',
        'aria-label': 'Filter ATMs',
      },
    });
    input.value = state.atmFilter ?? '';
    input.addEventListener('input', (e) => {
      state.atmFilter = e.target.value;
      renderAtmPicker();
    });
    filterBar.appendChild(input);
    const count = el('span', { class: 'atm-filter-count' });
    filterBar.appendChild(count);
    host.appendChild(filterBar);

    const matches = atms.filter((atm) => {
      if (!filter) return true;
      const hay = [
        atm.ATMId,
        atm.Location?.PostalAddress?.DistrictName,
        atm.Location?.PostalAddress?.TownName,
        atm.Location?.PostalAddress?.CountrySubDivision,
        atm.Location?.Site?.Name,
      ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();
      return hay.includes(filter);
    });
    count.textContent = `${matches.length} of ${atms.length}`;

    if (matches.length === 0) {
      host.appendChild(
        el('p', {
          class: 'atm-empty',
          text: filter ? 'No ATMs match this filter.' : 'No ATMs in this directory.',
        }),
      );
      return;
    }

    const list = el('div', { class: 'atm-list' });
    for (const atm of matches) {
      const isActive = atm.ATMId === state.atmId;
      const row = el('button', {
        class: `atm-row${isActive ? ' is-active' : ''}`,
        attrs: {
          type: 'button',
          role: 'option',
          'aria-selected': isActive ? 'true' : 'false',
        },
        dataset: { atmId: atm.ATMId },
        onClick: () => {
          if (state.atmId === atm.ATMId) return;
          state.atmId = atm.ATMId;
          renderAtmPicker();
          renderAtmPayload();
          pushPermalink();
        },
      });
      row.appendChild(el('span', { class: 'atm-row-id', text: atm.ATMId }));
      const where =
        [atm.Location?.PostalAddress?.DistrictName, atm.Location?.PostalAddress?.TownName]
          .filter(Boolean)
          .join(' · ') || '—';
      row.appendChild(el('span', { class: 'atm-row-where', text: where }));
      const status = atm.Availability?.Status;
      if (status) {
        row.appendChild(
          el('span', {
            class: `atm-row-status atm-row-status-${status.toLowerCase()}`,
            text: status,
          }),
        );
      }
      list.appendChild(row);
    }
    host.appendChild(list);
  }

  function renderAtmPayload() {
    const body = document.getElementById('payload-body');
    const epLabel = document.getElementById('endpoint-label');
    if (!body) return;
    body.replaceChildren();
    if (epLabel) epLabel.textContent = state.endpoint ?? '';

    document.getElementById('view-rendered')?.classList.toggle('active', state.view === 'rendered');
    document.getElementById('view-raw')?.classList.toggle('active', state.view === 'raw');
    document
      .getElementById('view-rendered')
      ?.setAttribute('aria-selected', state.view === 'rendered');
    document.getElementById('view-raw')?.setAttribute('aria-selected', state.view === 'raw');

    const atms = state.bundle?.atms ?? [];
    const meta = state.bundle?.meta ?? {};
    const selected = state.atmId ? atms.find((a) => a.ATMId === state.atmId) : null;

    const fields = leafFields(state.spec, state.endpoint);
    const fieldsByName = new Map();
    for (const f of fields) fieldsByName.set(f.name, f);

    if (state.view === 'raw') {
      const payload = selected ?? { Data: atms, Meta: meta };
      body.appendChild(
        el('pre', {
          class: 'payload-raw',
          text: JSON.stringify(payload, null, 2),
        }),
      );
      return;
    }

    const wrap = el('div', { class: 'payload-rendered atm-payload' });

    // Directory overview banner — shown even when an ATM is picked, so the
    // user always sees the fleet-level context (size, last updated, profile)
    // alongside the selected record.
    const overview = el('div', { class: 'atm-overview' });
    overview.appendChild(
      el('div', {
        class: 'atm-overview-line',
        text: `Directory: ${atms.length} ATM${atms.length === 1 ? '' : 's'} · profile ${state.lfi} · LFI ${state.bundle?.identity?.LFIId ?? '—'}`,
      }),
    );
    if (meta.LastUpdatedDateTime) {
      overview.appendChild(
        el('div', {
          class: 'atm-overview-line atm-overview-line-muted',
          text: `LastUpdatedDateTime · ${meta.LastUpdatedDateTime}`,
        }),
      );
    }
    if (!selected) {
      overview.appendChild(
        el('p', {
          class: 'atm-overview-hint',
          text: 'Pick an ATM from the directory rail to traverse its fields.',
        }),
      );
    }
    wrap.appendChild(overview);

    if (selected) {
      const card = el('div', { class: 'atm-record' });
      card.appendChild(el('div', { class: 'atm-record-header', text: selected.ATMId }));
      card.appendChild(renderFieldTree(selected, fieldsByName, el));
      wrap.appendChild(card);
    } else if (atms.length > 0) {
      // Empty-selection landing: render the first ATM's field tree
      // as a worked example so first-time visitors see what they'll get.
      const sample = atms[0];
      const card = el('div', { class: 'atm-record atm-record-sample' });
      card.appendChild(el('div', { class: 'atm-record-header', text: `Sample · ${sample.ATMId}` }));
      card.appendChild(renderFieldTree(sample, fieldsByName, el));
      wrap.appendChild(card);
    }

    body.appendChild(wrap);
  }

  return { renderAtmBundle };
}

// Reverse of showAtmPaneChrome(). Invoked from src/app.js:switchDomain when
// the user moves OUT of the ATM domain so the persona library + its filter
// rails re-appear.
export function restorePersonaPaneChrome() {
  const pane = document.querySelector('.persona-pane');
  if (!pane) return;
  pane.classList.remove('is-atm');
  const header = pane.querySelector('.pane-header .pane-header-text');
  if (header) header.textContent = 'Persona library';
  const rail = pane.querySelector('.pane-rail .pane-rail-label');
  if (rail) rail.textContent = 'Persona library';
  const list = document.getElementById('persona-list');
  if (list) {
    list.setAttribute('role', 'list');
    list.setAttribute('aria-label', 'Persona library');
  }
}
