// Domain dispatch — the registry-driven core shared by the sync full entry
// (src/generator/index.js, used by Node tooling/tests and the Service Worker)
// and the browser lazy entry (src/generator/lazy.js). Holds no per-domain
// imports of its own so the lazy entry can load domain pipelines on demand
// (C-P1 / EXP-24) without this module dragging them back in.
//
// A "pipeline" is `{ build(args), mergeInto(bundle, args) }` — see the
// modules under src/generator/pipelines/. Any domain missing from the
// registry passed to buildBundleWith is a hard error at build time, never a
// silent partial bundle (APP_IMPROVEMENT_PLAN.md §1 A-6).

// Bundle time anchor (EXP-05 / §8.3): the bundle is a pure function of
// (persona, lfi, seed, now); `now` defaults to this build-time anchor so two
// visitors hitting the same URL on different days see byte-identical bundles.
export const DEFAULT_NOW = new Date(Date.UTC(2026, 3, 1, 0, 0, 0));

// Canonical merge order for multi-domain bundles (banking → insurance → atm),
// NOT persona declaration order: merge order decides which side's scalars win
// on key collisions, so reordering a YAML `domains:` list must never change
// generated bytes (EXP-05). Also the closed set of known domains — the lazy
// entry validates against this before dynamic-importing anything.
export const DOMAIN_ORDER = ['banking', 'insurance', 'atm'];

/**
 * Resolve the persona's declared domain(s). Single-domain personas
 * carry `domain:` (string); Phase 2.2+ multi-domain personas declare
 * `domains:` (array). Returns an array.
 */
export function resolveDomains(persona) {
  if (Array.isArray(persona?.domains) && persona.domains.length > 0) {
    return persona.domains;
  }
  return [persona?.domain ?? 'banking'];
}

/**
 * Build a bundle using the given pipeline registry. Validates EVERY declared
 * domain up front — single- and multi-domain alike (A-6: an unknown domain is
 * a hard error, never a silently partial bundle).
 */
export function buildBundleWith(registry, args) {
  const domains = resolveDomains(args.persona);
  for (const domain of domains) {
    if (!registry[domain]) throw new Error(`unknown persona domain: ${domain}`);
  }
  if (domains.length === 1) {
    return registry[domains[0]].build(args);
  }
  return buildMultiDomainBundle(registry, { ...args, domains });
}

/**
 * Phase 2.2 — multi-domain persona dispatcher. Runs each declared domain's
 * pipeline for the same (persona, lfi, seed), then merges the resulting
 * bundles into a single flat object so `envelopesFromBundle` (export.js) can
 * emit every endpoint family at the same persona path.
 *
 * Determinism: all pipelines seed their main RNG with the same
 * (persona_id, 'generator', seed) tuple — the first draw on each side is the
 * name, so the persona's display name is identical across all halves.
 * Cross-pipeline RNG state is independent thereafter.
 */
function buildMultiDomainBundle(
  registry,
  { persona, lfi, seed, pools, now = DEFAULT_NOW, domains },
) {
  let bundle = {
    persona: persona.persona_id,
    name: persona.name,
    domains: [...domains],
  };

  for (const domain of DOMAIN_ORDER) {
    if (!domains.includes(domain)) continue;
    bundle = registry[domain].mergeInto(bundle, { persona, lfi, seed, pools, now });
  }

  return bundle;
}
