#!/usr/bin/env node
// Stage the built sandbox into _site/ — the directory shape Cloudflare
// Pages / Netlify / GitHub Pages all expect for static deploys. Copies
// src/ + dist/ + writes a top-level redirect into the app entry.
//
// Run after `npm run build:spec` and `node tools/build-data.mjs` so dist/
// already contains SPEC.json + data.json.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');
const out = path.join(repoRoot, '_site');

function rmrf(p) {
  if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true });
}

function cprf(src, dst) {
  fs.cpSync(src, dst, { recursive: true });
}

rmrf(out);
fs.mkdirSync(out, { recursive: true });

cprf(path.join(repoRoot, 'src'), path.join(out, 'src'));
cprf(path.join(repoRoot, 'dist'), path.join(out, 'dist'));

// EXP-21 / D-08 — self-host the PostHog SDK + ship a CSP-friendly
// external config script that hands the project key to src/analytics.js.
//
// Two files end up in _site/src/vendor/:
//   - posthog-js-<sha8>.js : the SDK itself, copied byte-for-byte from
//     node_modules/posthog-js/dist/module.slim.js. Hashed filename so
//     the browser can cache it forever; the hash flips when the npm
//     dep version bumps. We use the `slim` build (no recorder, no
//     surveys, no autocapture machinery) since EXP-21 disables all of
//     those — saves ~90 KB raw / ~28 KB gzipped vs the full module.
//   - posthog-config.js : a one-line script setting two globals,
//     `window.__POSTHOG_KEY__` (the public project key) and
//     `window.__POSTHOG_SDK_URL__` (the hashed SDK path). Loaded by a
//     normal `<script src=...>` in every entry HTML, so a strict
//     `script-src 'self'` CSP works without `'unsafe-inline'`.
//
// Project keys are public-by-design (every PostHog-using site ships
// theirs in client code). The reason to funnel through the GH Actions
// secret + an external config script is to keep the source tree clean,
// stay CSP-friendly, and let staging vs production diverge.
//
// When POSTHOG_KEY is unset (local `npm run serve`, fork build, deploy
// without secret access) the SDK file is still copied but the config
// file is not written and no `<script>` tag is injected. analytics.js
// then short-circuits to a no-op — the EXP-21 contract is never
// violated by a missing-key state.
//
// ⚠ Deploy-target gotcha: this env var must be set on whichever build
// container actually publishes to the production origin. Each platform
// is its own world:
//   - GitHub Pages: .github/workflows/deploy.yml passes
//     `secrets.POSTHOG_KEY` to the `npm run build:site` step. Set the
//     repo secret in GitHub → Settings → Secrets and variables → Actions.
//   - Cloudflare Pages: Cloudflare runs its own build container that
//     does NOT see GitHub Actions secrets. Set the env var in the
//     Cloudflare dashboard → Workers & Pages → <project> → Settings →
//     Environment variables (Production scope), then redeploy.
//   - Netlify / Vercel / Fly: same pattern — set the env var on the
//     platform that builds, not on GitHub Actions.
// If you wire a new deploy target and forget this step, the deployed
// `data-sandbox.<host>/src/vendor/posthog-config.js` 404s and
// analytics.js logs `POSTHOG_KEY not configured` in DevTools console.
const SDK_SRC = path.join(repoRoot, 'node_modules/posthog-js/dist/module.slim.js');
const stagedVendor = path.join(out, 'src', 'vendor');
fs.mkdirSync(stagedVendor, { recursive: true });

const sdkBytes = fs.readFileSync(SDK_SRC);
const sdkSha = crypto.createHash('sha256').update(sdkBytes).digest('hex').slice(0, 8);
const sdkFilename = `posthog-js-${sdkSha}.js`;
fs.writeFileSync(path.join(stagedVendor, sdkFilename), sdkBytes);

const posthogKey = process.env.POSTHOG_KEY ?? '';
if (posthogKey) {
  // Sanity check the shape — PostHog project keys start with `phc_`. If
  // a contributor pastes the personal-API key by mistake the deploy
  // should fail loudly here rather than ship a broken bundle.
  if (!/^phc_[A-Za-z0-9]+$/.test(posthogKey)) {
    throw new Error(
      "[stage-site] POSTHOG_KEY does not look like a PostHog project key (expected /^phc_[A-Za-z0-9]+$/). Refusing to inject — check the secret value."
    );
  }
  // Leading `./` is load-bearing — `import()` resolves bare-relative
  // specifiers like `vendor/foo.js` as bare module specifiers, not
  // path-relative URLs (HTML spec "Resolve a Module Specifier"), and
  // throws TypeError when no import map is in scope.
  const configBody =
    `// Auto-generated by tools/stage-site.mjs. Edit there, not here.\n` +
    `window.__POSTHOG_KEY__ = ${JSON.stringify(posthogKey)};\n` +
    `window.__POSTHOG_SDK_URL__ = ${JSON.stringify('./vendor/' + sdkFilename)};\n`;
  fs.writeFileSync(path.join(stagedVendor, 'posthog-config.js'), configBody);
  const injection = `<script src="vendor/posthog-config.js"></script>`;
  const stagedSrc = path.join(out, 'src');
  let injectedCount = 0;
  for (const entry of fs.readdirSync(stagedSrc)) {
    if (!entry.endsWith('.html')) continue;
    const p = path.join(stagedSrc, entry);
    const html = fs.readFileSync(p, 'utf8');
    if (!html.includes('</head>')) continue;
    fs.writeFileSync(p, html.replace('</head>', `${injection}\n</head>`));
    injectedCount += 1;
  }
  console.log(`[stage-site] vendored ${sdkFilename} (${(sdkBytes.length / 1024).toFixed(1)} KB) + posthog-config.js into ${injectedCount} entry HTML(s)`);
} else {
  console.log(`[stage-site] vendored ${sdkFilename} (${(sdkBytes.length / 1024).toFixed(1)} KB); POSTHOG_KEY not set so no posthog-config.js was emitted — analytics will be off in this build`);
}

// Stage the worked TPP example so the integration guide's link resolves
// at the deployed origin and a TPP can preview the journey live.
const examplesSrc = path.join(repoRoot, 'examples');
if (fs.existsSync(examplesSrc)) {
  cprf(examplesSrc, path.join(out, 'examples'));
}

// EXP-28 — publish the fixture package as raw HTTPS-fetchable JSON under
// /fixtures/v1/ so TPP integrations not on Node/Python (Swift, Kotlin,
// Postman, Flutter, .NET, plain curl) can consume the same dataset the
// npm/PyPI packages ship. Path slot `/v1/` is the major-version boundary
// (PRD §13 D-11). Within v1, evolution is additive only.
const fixtureSrc = path.join(repoRoot, 'packages/sandbox-fixtures');
if (fs.existsSync(path.join(fixtureSrc, 'manifest.json'))) {
  const fixtureDst = path.join(out, 'fixtures/v1');
  fs.mkdirSync(fixtureDst, { recursive: true });
  cprf(path.join(fixtureSrc, 'bundles'), path.join(fixtureDst, 'bundles'));
  cprf(path.join(fixtureSrc, 'personas'), path.join(fixtureDst, 'personas'));
  // Phase R1.5 — per-(persona, seed) enrichment sidecar dataset. Same
  // CORS posture as bundles/ (declared in _site/_headers below); served
  // at /fixtures/v1/enrichment/<persona>/seed-<n>.json.
  if (fs.existsSync(path.join(fixtureSrc, 'enrichment'))) {
    cprf(path.join(fixtureSrc, 'enrichment'), path.join(fixtureDst, 'enrichment'));
  }
  fs.copyFileSync(path.join(fixtureSrc, 'manifest.json'), path.join(fixtureDst, 'manifest.json'));
  fs.copyFileSync(path.join(fixtureSrc, 'spec.json'), path.join(fixtureDst, 'spec.json'));

  // Discovery doc — a TPP-friendly summary so consumers don't have to walk
  // the full manifest just to learn the shape (which personas, which LFIs,
  // which endpoints exist). Mirrors what loadJourney() returns.
  const m = JSON.parse(fs.readFileSync(path.join(fixtureDst, 'manifest.json'), 'utf8'));
  const personaIds = Object.keys(m.personas);
  const sampleKey = personaIds.length ? `${personaIds[0]}|median|${m.personas[personaIds[0]].default_seed}` : null;
  const allEndpoints = sampleKey && m.fixtures[sampleKey] ? Object.keys(m.fixtures[sampleKey].endpoints) : [];
  // Show only canonical v2.1 endpoint paths (templated `{AccountId}` and
  // bundle-level paths). Persona-specific resolved paths exist in the
  // manifest for callers that need them, but they're noise in discovery.
  const endpoints = allEndpoints.filter((e) => !/^\/accounts\/[^{][^/]*(\/|$)/.test(e));
  const index = {
    schema: 'openfinance-os/data-sandbox/fixtures/v1',
    version: m.version,
    specVersion: m.specVersion,
    specSha: m.specSha,
    generatedAt: m.generatedAt,
    nowAnchor: m.nowAnchor,
    personas: personaIds.map((id) => ({ id, ...m.personas[id] })),
    lfiProfiles: ['rich', 'median', 'sparse'],
    endpoints,
    pathContract: '/fixtures/v1/bundles/<persona>/<lfi>/seed-<n>/<endpoint>.json',
    pin: 'manifest.json.version',
    pinNote: 'For high-stakes consumption pin via the npm/PyPI package (immutable). Raw URLs are latest-only within the /v1/ major slot.',
  };
  fs.writeFileSync(path.join(fixtureDst, 'index.json'), JSON.stringify(index, null, 2));
} else {
  console.warn('[stage-site] fixtures not built — /fixtures/v1/ will be missing. Run `npm run build:fixtures` first.');
}

// Top-level redirect into the app entry so the bare URL works.
const indexHtml = `<!doctype html>
<html><head><meta charset="utf-8"/>
<title>Open Finance Data Sandbox</title>
<meta http-equiv="refresh" content="0; url=src/index.html"/>
<link rel="canonical" href="src/index.html"/>
</head><body><p>Redirecting to <a href="src/index.html">the sandbox</a>…</p></body></html>
`;
fs.writeFileSync(path.join(out, 'index.html'), indexHtml);

// .nojekyll so GitHub Pages skips Jekyll. Harmless on Cloudflare/Netlify.
fs.writeFileSync(path.join(out, '.nojekyll'), '');

// Optional Netlify / Cloudflare Pages _headers file — long-cache for
// hashed assets, short-cache for HTML so deploys propagate quickly.
// /fixtures/v1/* is CORS-permissive (EXP-28) so TPP demos hosted on a
// different origin can fetch them from the browser.
//
// Deploy-target nuance (the v0.10 review watch item):
//   - The current production deploy (.github/workflows/deploy.yml) targets
//     GitHub Pages, which DOES NOT honor `_headers` directives — so the
//     `Cache-Control` lines below are best-effort defaults only.
//   - GitHub Pages DOES serve `Access-Control-Allow-Origin: *` by default
//     on every static asset, so the EXP-28 cross-origin-fetch contract
//     still holds in practice on GH Pages even though our `_headers` file
//     is silently ignored. This is verified at runtime by
//     `tests/integrate-staging.test.mjs` and asserted against the deployed
//     origin in the e2e suite.
//   - On Netlify / Cloudflare Pages (the eventual OF-OS Commons target)
//     these directives do take effect verbatim.
// The file is emitted regardless so a host migration is drop-in.
const headers = `/dist/*
  Cache-Control: public, max-age=600, must-revalidate

/src/*.js
  Cache-Control: public, max-age=600, must-revalidate

/src/*.html
  Cache-Control: public, max-age=60, must-revalidate

/fixtures/v1/*
  Cache-Control: public, max-age=600, must-revalidate
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: GET, HEAD, OPTIONS
`;
fs.writeFileSync(path.join(out, '_headers'), headers);

const totalBytes = walkSize(out);
console.log(`staged → ${path.relative(repoRoot, out)} (${(totalBytes / 1024).toFixed(1)} KB)`);

function walkSize(dir) {
  let total = 0;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) total += walkSize(p);
    else total += fs.statSync(p).size;
  }
  return total;
}
